import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';
import {readFree,buildFree} from '../scripts/free-project.mjs';import {indexCases,searchCases} from '../scripts/cases.mjs';import {parseSrt} from '../scripts/captions.mjs';
function fixture(fn){const d=fs.mkdtempSync(path.join(os.tmpdir(),'motion-free-'));try{for(const [f,c]of Object.entries({'font.ttf':'font','gsap.js':'code','a.html':'<h1>你好</h1>','a.css':'','a.js':''}))fs.writeFileSync(path.join(d,f),c);const m={mode:'free',width:1280,height:720,fps:30,totalFrames:150,font:'font.ttf',gsap:'gsap.js',scenes:[{id:'a',start:0,frames:150,html:'a.html',css:'a.css',js:'a.js'}],media:[]};const save=()=>fs.writeFileSync(path.join(d,'project.json'),JSON.stringify(m));save();fn(d,m,save);}finally{assert.ok(d.startsWith(path.join(os.tmpdir(),'motion-free-')));fs.rmSync(d,{recursive:true,force:true});}}
test('free arbitrary HTML source compiles and is hashed',()=>fixture((d)=>{buildFree(d);assert.match(fs.readFileSync(path.join(d,'index.html'),'utf8'),/你好/);const r=JSON.parse(fs.readFileSync(path.join(d,'reports/build.json')));assert.ok(r.sourceHashes['a.html']);}));
test('overlap permitted for transition',()=>fixture((d,m,save)=>{m.scenes[0].frames=90;m.scenes.push({...m.scenes[0],id:'b',start:75,frames:75});save();assert.equal(readFree(d).frames.length,2);}));
for(const [name,mutate]of Object.entries({gap:m=>m.scenes[0].start=1,fraction:m=>m.scenes[0].frames=149.5,duplicate:m=>m.scenes.push({...m.scenes[0]}),escape:m=>m.scenes[0].html='../outside.html'}))test(`free rejects ${name}`,()=>fixture((d,m,save)=>{mutate(m);save();assert.throws(()=>readFree(d));}));
test('unlisted local image is captured by build',()=>fixture((d)=>{fs.writeFileSync(path.join(d,'img.png'),'image');fs.writeFileSync(path.join(d,'a.html'),'<img src="img.png">');buildFree(d);assert.ok(JSON.parse(fs.readFileSync(path.join(d,'reports/build.json'))).sourceHashes['img.png']);}));
test('external image rejected before rendering',()=>fixture(d=>{fs.writeFileSync(path.join(d,'a.html'),'<img src="https://example.org/a.png">');assert.throws(()=>buildFree(d),/Localize/);}));
test('case provenance and duplicate retained',()=>{const r=indexCases([{slug:'a',prompt:'Fold paper',author:'one'},{slug:'b',prompt:'fold   PAPER',prompt_partial:true}]);assert.equal(r[1].duplicateOf,'a');assert.equal(searchCases(r,'纸张').length,1);assert.equal(r[0].raw.author,'one');});
test('SRT times become exact frame intervals',()=>assert.deepEqual(parseSrt('1\n00:00:00,500 --> 00:00:01,000\n中文',30),[{start:15,end:30,text:'中文'}]));
test('overlap subtitles rejected',()=>assert.throws(()=>parseSrt('1\n00:00:00,000 --> 00:00:02,000\na\n\n2\n00:00:01,000 --> 00:00:03,000\nb',30)));
