import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';import os from 'node:os';import {spawnSync} from 'node:child_process';import {hash,SKILL} from '../scripts/project.mjs';
function fixture(fn){const d=fs.mkdtempSync(path.join(os.tmpdir(),'motion-release-'));try{fs.mkdirSync(path.join(d,'reports'));fs.mkdirSync(path.join(d,'renders'));for(const [f,v]of Object.entries({'index.html':'html','source.html':'source','renders/final.mp4':'unit fixture, not real video','reports/frame.png':'unit frame'}))fs.writeFileSync(path.join(d,f),v);const put=(f,obj)=>fs.writeFileSync(path.join(d,f),JSON.stringify(obj));put('reports/build.json',{indexSha256:hash(path.join(d,'index.html')),sourceHashes:{'source.html':hash(path.join(d,'source.html'))}});const b=hash(path.join(d,'reports/build.json')),v=hash(path.join(d,'renders/final.mp4'));put('reports/qc-report.json',{status:'passed',sha256:v});put('reports/render-receipt.json',{buildSha256:b,videoSha256:v});const review={buildSha256:b,videoSha256:v,reviewer:'unit fixture',decision:'ready-for-user-review',evidence:[{file:'reports/frame.png',time:1,observation:'fixture'}],criteria:[{name:'type',observation:'fixture',status:'reviewed'}]};put('reports/art-review.json',review);const check=()=>spawnSync(process.execPath,[path.join(SKILL,'scripts/release-check.mjs'),d],{encoding:'utf8'});fn(d,review,put,check);}finally{assert.ok(d.startsWith(path.join(os.tmpdir(),'motion-release-')));fs.rmSync(d,{recursive:true,force:true});}}
test('release evidence matching is separate from user approval',()=>fixture((d,r,p,check)=>{const out=check();assert.equal(out.status,0);assert.match(out.stdout,/does not constitute user approval/);}));
test('release rejects unresolved art criticism',()=>fixture((d,r,p,check)=>{r.criteria[0].status='revise';p('reports/art-review.json',r);assert.notEqual(check().status,0);}));
test('release rejects source edited after review',()=>fixture((d,r,p,check)=>{fs.writeFileSync(path.join(d,'source.html'),'changed');assert.notEqual(check().status,0);}));
test('release rejects missing visual evidence',()=>fixture((d,r,p,check)=>{r.evidence[0].file='reports/missing.png';p('reports/art-review.json',r);assert.notEqual(check().status,0);}));
for(const status of [undefined,'pending','failed','unknown'])test(`release rejects criterion status ${status}`,()=>fixture((d,r,p,check)=>{r.criteria[0].status=status;p('reports/art-review.json',r);assert.notEqual(check().status,0);}));
test('release rejects negative evidence time',()=>fixture((d,r,p,check)=>{r.evidence[0].time=-1;p('reports/art-review.json',r);assert.notEqual(check().status,0);}));
test('release rejects directory as frame evidence',()=>fixture((d,r,p,check)=>{r.evidence[0].file='reports';p('reports/art-review.json',r);assert.notEqual(check().status,0);}));
test('release rejects whitespace reviewer',()=>fixture((d,r,p,check)=>{r.reviewer='  ';p('reports/art-review.json',r);assert.notEqual(check().status,0);}));
