import fs from 'node:fs';
import path from 'node:path';
import {SKILL} from './project.mjs';
const [target,audio]=process.argv.slice(2);
if(!target)throw new Error('Usage: node init.mjs PROJECT [AUDIO_FILE]');
const dir=path.resolve(target);
if(fs.existsSync(dir)&&fs.readdirSync(dir).length)throw new Error('Choose an empty/new project folder');
const font=path.join(SKILL,'assets/NotoSansSC.ttf');
if(!fs.existsSync(font))throw new Error('Bundled font missing');
if(audio&&!fs.existsSync(path.resolve(audio)))throw new Error('Audio source not found');
fs.mkdirSync(path.join(dir,'assets'),{recursive:true});
for(const name of ['NotoSansSC.ttf','OFL.txt'])fs.copyFileSync(path.join(SKILL,'assets',name),path.join(dir,'assets',name));
fs.copyFileSync(path.join(SKILL,'node_modules/gsap/dist/gsap.min.js'),path.join(dir,'assets/gsap.min.js'));
const audioName=audio?`assets/audio${path.extname(audio)}`:'none';
if(audio)fs.copyFileSync(path.resolve(audio),path.join(dir,audioName));
fs.writeFileSync(path.join(dir,'BRIEF.md'),`---\nworkflow: gpt-motion-director\nflow: automation\nlanguage: zh-CN\n---\n\n## Intent\n记录用户的用途、受众、核心信息与交付要求。\n\n## Assets\n- ${audioName}\n\n## Notes\nSTORYBOARD.md 是画面文案、风格和时间轴的唯一编辑来源。\n`);
let text=`---\nformat: 1280x720\nfps: 30\ntotal_frames: 450\nduration: 15s\nmessage: 一个新的开始\nstrategy: showcase\naccent: #d67549\nfont: assets/NotoSansSC.ttf\ngsap: assets/gsap.min.js\naudio: ${audioName}\naudio_required: ${Boolean(audio)}\nsync_required: false\n---\n`;
for(let i=0;i<3;i++)text+=`\n## Frame ${i+1} — 场景 ${i+1}\n- start_frame: ${i*150}\n- frames: 150\n- duration: 5s\n- transition_in: cut\n- src: index.html\n- status: outline\n- scene: ${['引入主题','呈现变化','留下结论'][i]}\n- headline: ${['新的故事，|从这里开始。','让想法，|有了形状。','带着期待，|继续出发。'][i]}\n- subline: 请根据简报改写这一行。\n- eyebrow: 创作 / 新的开始\n- tag: 概念样片\n- footer: 让每一个画面服务于内容。\n`;
fs.writeFileSync(path.join(dir,'STORYBOARD.md'),text);
fs.writeFileSync(path.join(dir,'hyperframes.json'),JSON.stringify({name:path.basename(dir)},null,2));
console.log(dir);
